name: Run Pytest

# Triggers the workflow on push or pull request events for the main branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:
    branches: ["main"]

# A workflow can have multiple independent jobs. Each job gets a fresh VM.
jobs:
  test: # This is simply the job's ID. It could be anything: like backend-tests or something like that
    runs-on: ubuntu-latest

    steps: A list of things to execute in order.
      # Step 1: Download a copy of your code onto the GitHub runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install and configure Python on the runner
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14" # Change to your preferred Python version

      # Step 3: Upgrade pip and install project dependencies
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest tests/test_files_routes.py
